spring:
  application:
    name: hypercharge-batch
  profiles:
    include:
      - domain
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

brawlstars:
  api:
    base-url: https://api.brawlstars.com/v1
    key: ${BRAWLSTARTS_API_KEY}

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  chat-id: ${TELEGRAM_CHAT_ID}
  enabled: ${TELEGRAM_ENABLED}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.batch: INFO
